### ISSUE TITLE
Feel free to add resources.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/Lecture-Series-PHP#1]
Add PHP content that you will be referring for PHP Lectures.
Feel free to add more resources if you find any.

**Comment by punit-agarwal** [comment]
https://drive.google.com/file/d/0B2yr1MdsvFg9c25yLU9oWk1EUm8/view?usp=sharing

Lynn Beighley, Michael Morrison Head First PHP & MySQL A Brain-Friendly Guide PDF

**Comment by divyanshu-rawat** [comment]
@punit-agarwal It would be great if you clone and push the resource shared by you in this repo. itself.

**Comment by punit-agarwal** [comment]
https://drive.google.com/drive/folders/0B2t-Tmujl-IbTXAtZUthNWtscGc?usp=sharing

LYNDA PHP-ESSENTIALS CRACKED COURSE (Tutorials + Exercises)

**Comment by divyanshu-rawat** [comment]
@punit-agarwal  It would be great if you clone and push the resource shared by you in this repo. itself.
